
import { Asset } from 'expo-asset';

const images = {
    'PLAYER1' : require('../images/gameIcons/p1.png'),
    'PLAYER2' : require('../images/gameIcons/p2.png'),
    'PLAYER3' : require('../images/gameIcons/dM.png'),
    'PLAYER4' : require('../images/gameIcons/Hm.png'),
    'DISK1' : require('../images/gameIcons/disk1.png'),
    'DISK2' : require('../images/gameIcons/disk2.png'),
    'DISK3' : require('../images/gameIcons/disk3.png'),
    'FO' : require('../images/gameIcons/FO.png'),
    'FOOTBALL' : require('../images/gameIcons/football.png'),
    'M' : require('../images/gameIcons/m.png'),
    'NET1' : require('../images/gameIcons/net1.png'),
    'NET2' : require('../images/gameIcons/net2.png'),
    'NET3' : require('../images/gameIcons/net3.png'),
    'NET4' : require('../images/gameIcons/net4.png'),
    'QB' : require('../images/gameIcons/qB.png'),
    'RING1' : require('../images/gameIcons/ring1.png'),
    'RING2' : require('../images/gameIcons/ring2.png'),
    'TRI1' : require('../images/gameIcons/tri1.png'),
    'TRI2' : require('../images/gameIcons/tri2.png'),
    'TRI3' : require('../images/gameIcons/tri3.png'),
    'UZ' : require('../images/gameIcons/UZ.png'),
    'Y8' : require('../images/gameIcons/y8.png'),
    'a-football' : require('../images/stadium/a-football.png'),
    'bg-football' : require('../images/stadium/Football.png'),
    'bascket' : require('../images/stadium/bascket.png'),
    'cricket' : require('../images/stadium/cricket.png'),
    'Hokey' : require('../images/stadium/Hokey.png'),
    'Rugby' : require('../images/stadium/Rugby.png'),
    'stadium' : require('../images/stadium/stadium.png'),
    'ball1': require('../images/gameIcons/ball1.png'),
    'ball2': require('../images/gameIcons/ball2.png'),
    'ball3': require('../images/gameIcons/ball3.png'),
    'ball4': require('../images/gameIcons/ball4.png'),
    'ball5': require('../images/gameIcons/ball5.png'),
    'p1' : require('../images/gameIcons/p1.png'),
    'p2' : require('../images/gameIcons/p2.png'),
    'p3' : require('../images/gameIcons/p3.png'),
    'p4' : require('../images/gameIcons/p4.png'),
    'p5' : require('../images/gameIcons/p5.png'),
}

export default images;